import { StyleSheet } from 'react-native';
import { DPW } from '../../dp';
export const styles = StyleSheet.create({
  container: {},
  headerText: {
    paddingTop: 30 * DPW,
    alignItems: 'center',
    fontSize: 70 * DPW,
    color: 'white',
    top: 75 * DPW,
    fontFamily: 'BMJUA',
  },
  bodyContainer: {
    backgroundColor: '#191970',
    paddingHorizontal: 20 * DPW,
    marginVertical: 30 * DPW,
    width: 550 * DPW,
    top: 100 * DPW,
  },
  idInput: {
    fontFamily: 'BMJUA',
    marginTop: 20 * DPW,
    marginBottom: 10 * DPW,
    paddingHorizontal: 10 * DPW,
    height: 120 * DPW,
    paddingLeft: 30 * DPW,
    borderRadius: 10 ,
    backgroundColor: 'white',
    borderWidth: 3,
    color: '#191970',
    fontSize: 38 * DPW,
  },
  pwdInput: {
    // fontFamily:"BMJUA",
    marginTop: 20 * DPW,
    marginBottom: 10 * DPW,
    paddingHorizontal: 15 * DPW,
    height: 120 * DPW,
    borderRadius: 10,
    paddingLeft: 30 * DPW,
    backgroundColor: '#E6E6FA',
    borderWidth: 3,
    color: '#191970',
    fontSize: 38 * DPW ,
  },
  showText: {
    marginTop: 30 * DPW,
    fontSize: 25* DPW ,
    color: 'white',
  },
  loginBtnContainer: {
    backgroundColor: '#AFEEEE',
    height: 80 * DPW,
    alignItems: 'center',
    borderRadius: 20,
    borderWidth: 3,
    borderColor: 'white',
    marginTop: 30 * DPW,
  },
  loginBtn: {
    alignItems: 'center',
    fontFamily: 'BMJUA',
    fontSize: 50 * DPW,
    color: '#191970',
    marginTop: 12 * DPW,
  },
});
